channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip
  - libpdal-core=2.9.3
  - libpdal-e57=2.9.3
  - pip:
      - streamlit==1.63.0
      - plotly==6.9.0
      - numpy==2.5.3
      - laspy==2.7.0
      - pyproj==3.8.0
      - lazrs
